### ISSUE TITLE
Regarding Slices... 

### ISSUE THREAD

**Issue by rylanharper** [ilrock/gridsome-starter-prismic#5]
Ehyo! 👋 Thanks for making this plugin!

I have a few questions regarding slices within posts as there isn't much on the docs here about it and its probably the main feature of Prismic (other than the free imgix 😜) 

I am new to using GraphQL with Prismic, but generally structure my slices in a `slices` folder then create corresponding `.vue` components for each one. Finally, I loop over them in my post/repeatable types. For slices using GraphQL, I found this [post](https://prismic.io/docs/graphql/query-the-api/retrieve-slice-content) on the Prismic docs on how to query slices, but I am curious how to go about structuring slices in a post with this plugin.. Is it just listing the GraphQL data within the `page-query` the post/repeatable type then making a loop over slices? It would be nice to see a simple example of that in this starter.

**Comment by MarcelloTheArcane** [comment]
Here's what I did:

``` vue
<!-- templates/Page.vue -->

<template>
  <layout>
    <component
      v-for="(slice, index) in $page.prismicio.allPages.edges[0].node.body"
      :key="index"
      :is="componentLookup(slice.type)"
      :slice="slice"
    />
  </layout>
</template>

<page-query>
query ($url: String!) {
  prismicio {
    allPages (
      where: {
        page_url: $url
      }
    ) {
      edges {
        node {
          // Query all the nodes
        }
      }
    }
  }
}
</page-query>

<script>
// import all the slices

export default {
  name: 'Page',
  components: {
    // all the slices
  },
  methods: {
    componentLookup (type) {
      const lookup = {
        // object with prismic_type: 'SliceName' format
      }

      return lookup[type]
    }
  }
}
```

Then each slice is like this:

``` vue
<!-- components/slices/SliceName.vue -->

<template>
  <div>
    {{ slice }} <!-- do stuff with slice data -->
  </div>
</template>

<script>
export default {
  name: 'SliceName',
  props: {
    slice: {
      type: Object,
      required: true
    }
  }
}
</script>
```

**Comment by rylanharper** [comment]
Thank you for that example! I’ll go ahead and try that out:)
